name: Disenchantments
version: 1.1
main: peterhenryd.disenchantments.Disenchantments
api-version: 1.16
softdepend:
  - mcMMO
commands:
  disenchant:
    description: The command for disenchanting tools.
  disenchantments:
    description: The administrative command for Disenchantments.